### ISSUE TITLE
VB.NET - Yes I am old school - Trying to get a rule to exclude public holidays around Xmas

### ISSUE THREAD

**Issue by alexstanier** [diaconesq/RecurringDates#2]
I am struggling a bit with the syntax. I am defining the dates from Dec 22nd to Jan 2nd which I want to protect. I realise I am missing a few in the middle.

What is happening is that it is not excluding the holiday period that I want excluded so it is including meetings on Christmas Day and New Year's Day which.. I am not keen on.

How could I simplify the following code?

```
    Dim the22nd = New NthInMonthRule
    the22nd.Nth = 22
    Dim the23rd = New NthInMonthRule
    the23rd.Nth = 23
    Dim the24th = New NthInMonthRule
    the24th.Nth = 24
    Dim the25th = New NthInMonthRule
    the25th.Nth = 25
    Dim the26th = New NthInMonthRule
    the26th.Nth = 26
    Dim the31st = New NthInMonthRule
    the31st.Nth = 31
    Dim the1st = New NthInMonthRule
    the1st.Nth = 1
    Dim the2nd = New NthInMonthRule
    the2nd.Nth = 2
```

Then I define the rules per day. I realise there must be a one line way to achieve this.

```
    Dim NotXmasEveEveEve As IRule = the22nd.InMonths(Month.Dec).Not()
    Dim NotXmasEveEve As IRule = the23rd.InMonths(Month.Dec).Not()
    Dim NotXmasEve As IRule = the24th.InMonths(Month.Dec).Not()
    Dim NotXmas As IRule = the25th.InMonths(Month.Dec).Not()
    Dim NotBoxingDay As IRule = the26th.InMonths(Month.Dec).Not()
    Dim NotNewYearsEve As IRule = the31st.InMonths(Month.Dec).Not()
    Dim NotNewYearsDay As IRule = the1st.InMonths(Month.Jan).Not()
    Dim NotNewYearsDayAfter As IRule = the2nd.InMonths(Month.Jan).Not()
    Dim NotChristmasNewYearRange As New NthDayBeforeAfterRule
    'ChristmasNewYearRange.Or(New IRule() {Xmas, XmasEve, BoxingDay, NewYearsEve, NewYearsDay, NewYearsDayAfter})

    Dim mtgdayrule As DayOfWeekRule
        mtgdayrule = DayOfWeek.Friday.EveryWeek()
```

And here I try to define my completed rule which is meant to be Fridays not Holidays. I would really just like a rule that says "From date X to date Y, every {DayOfWeek} where not in holiday period".

```
    Dim mtgdaynotHolidays = mtgdayrule.IfAlso(NotXmasEveEveEve, NotXmasEveEve, NotXmasEve, NotXmas, NotBoxingDay, NotNewYearsEve, NotNewYearsDay, NotNewYearsDayAfter)

    'MsgBox(notHolidays.GetDescription)

    If Not (IsNothing(StartDate)) And IsDate(StartDate) Then
        ' Is FinishDate Valid?
        If Not (IsNothing(FinishDate)) And IsDate(FinishDate) Then
            ' Is FinishDate greater than StartDate?
            If StartDate < FinishDate Then
                ' Delete all the old meetings
                intOldTotalMeetings = DeleteMeetings()
                ' loop from StartDate
                nextEventDate = New DateTime(StartDate.Year, StartDate.Month, StartDate.Day)
                While nextEventDate < FinishDate
                    '   Work out next date
                    nextEventDate = nextEventDate.AddDays(1)
                    '   If nextdate is less than or equal to finishdate, add it to the list
                    If nextEventDate <= FinishDate Then
                        ' If date is in range
```

*\* And here at last I try the check
                            mtgdaynotHolidays.IsMatch(New DateTime(nextEventDate.Year, nextEventDate.Month, nextEventDate.Day))
                            If mtgdaynotHolidays.IsMatch(New DateTime(nextEventDate.Year, nextEventDate.Month, nextEventDate.Day)) = True Then ' And ExcludeKeyDates(nextEventDate) _

Many thanks in advance

Alex
alex.stanier@caltrics.com

**Comment by diaconesq** [comment]
Hello!

Thanks for the feedback - this validates some assumptions on how my library
is used in the wild.

You are right, it should be easier to accomplish what you need.
I have updated the library with some new rules and helper methods, to help
in cases similar to yours.
Please update (using NuGet) to version 0.7.0 then look at my suggestions
below.

I have written an unit test specifically for your use case - see it here
(it is the last one, so scroll all the way down)
https://github.com/diaconesq/RecurringDates/blob/master/RecurringDates.UnitTests/RealWorldRules.cs

(Or see it reproduced below:)

```
[Test]
public void SkipXmasHolidays()
    {
        var holidayDays = new IRule[]
        {
            Month.Dec.Day(22),
            Month.Dec.Day(23),
            Month.Dec.Day(24),
            Month.Dec.Day(25),
            Month.Dec.Day(26),
            Month.Dec.Day(31),

            Month.Jan.Day(1),
            Month.Jan.Day(2),
        }.MatchAny();

        var weekDaysExceptHolidays = new WorkDayRule().Except(holidayDays);

        var startDate = new DateTime(2015, 12, 20);
        var endDate = new DateTime(2016, 1, 5);

        var boundedRule = weekDaysExceptHolidays.Between(startDate, endDate);

        var actualMatchingDays = boundedRule.MatchingDates;

        actualMatchingDays.Should().BeEquivalentTo(
            //Dec 20 is a sunday
            new DateTime(2015, 12, 21),
            //dec 22-26 are holidays
            //dec 27 is a sunday
            new DateTime(2015, 12, 28),
            new DateTime(2015, 12, 29),
            new DateTime(2015, 12, 30),
            //dec 31 - jan 2 are holidays
            //jan 3 is a sunday
            new DateTime(2016, 1, 4),
            new DateTime(2016, 1, 5)
            );
    }
```

I can't write VB.NET to save my life, but this is what a decompiler
generated from my unit test:

```
       Dim ruleArray() As IRule = { Month.Dec.Day(22),
```

Month.Dec.Day(23), Month.Dec.Day(24), Month.Dec.Day(25), Month.Dec.Day(26),
Month.Dec.Day(31), Month.Jan.Day(1), Month.Jan.Day(2) }
            Dim holidayDays As SetUnionRule = ruleArray.MatchAny()
            Dim weekDaysExceptHolidays As SetDifferenceRule = (New
WorkDayRule()).Except(holidayDays)
            Dim startDate As System.DateTime = New System.DateTime(2015,
12, 20)
            Dim endDate As System.DateTime = New System.DateTime(2016, 1, 5)
            Dim boundedRule As IEnumerableRule =
weekDaysExceptHolidays.Between(startDate, endDate)
            Dim genericCollectionAssertion As
GenericCollectionAssertions(Of System.DateTime) =
boundedRule.MatchingDates.Should(Of System.DateTime)()

I find it easier (in this scenario) to use positive logic.
The first rule matches any of the 'holiday' days (using the newly added
'day of month' rule and syntax, and the new,shorter '.MatchAny()' helper).
The 2nd rule matches all work days (Mon-Fri) _except_ the holiday days
(nothing new here :).
The 3rd rule applies (new) bounding dates to the 2nd rule (from startDate
to endDate)
This new rule type also exposes a property (MatchingDates) that gives an
enumeration of all actual days within the bound that actually match the
rule.

Hope this helps!
Don't hesitate to write if you have more questions!

**Comment by diaconesq** [comment]
By the way, I think I know why your example does not work: 
You define some negative rules: notXmasEve, notXmas etc that you later combine with OR:

```
ChristmasNewYearRange.Or(New IRule() {Xmas, XmasEve, ...
```

This generates an expression along these lines:

(not XmasEve) OR (not Xmas) OR (not ...) -> this expression always matches, for any day. 

What you want is : not ( XmasEve OR Xmas OR ...) 
This is equivalent with (not XmasEve) AND (not Xmas) AND (not ...).

Let me know if this solves your question.

**Comment by diaconesq** [comment]
@alexstanier feel free to reopen if you still encounter issues

**Comment by alexstanier** [comment]
Hi Cristian,

I do apologise for not replying sooner. I’ve just had a really busy week with other projects so this one had to wait.

I hope to test a bit more tonight following your instructions.

Alex

**Comment by diaconesq** [comment]
No need to apologize. If there's anything I can help out with, let me know. 
I'm very interested in improving the user experience (and the feature set), so I'd love getting some feedback - positive or negative.

**Comment by alexstanier** [comment]
Hi Cristian,

I’m now working on this.

Is it possible to also add Easter Friday (Good Friday) to the list of dates
03-Apr-15

Good Friday 2015

25-Mar-16

Good Friday 2016

14-Apr-17

Good Friday 2017

30-Mar-18

Good Friday 2018

19-Apr-19

Good Friday 2019

10-Apr-20

Good Friday 2020

02-Apr-21

Good Friday 2021

15-Apr-22

Good Friday 2022

07-Apr-23

Good Friday 2023

29-Mar-24

Good Friday 2024

18-Apr-25

Good Friday 2025

And in your email below, I don’t quite follow

“This new rule type also exposes a property (MatchingDates) that gives an
enumeration of all actual days within the bound that actually match the
rule.”

I also struggled in my code to test for a date calculated by me, or pulled from a data field was in the range to be tested.
I ended up with
                            mtgdaynotHolidays.IsMatch(New DateTime(nextEventDate.Year, nextEventDate.Month, nextEventDate.Day))
                            If mtgdaynotHolidays.IsMatch(New DateTime(nextEventDate.Year, nextEventDate.Month, nextEventDate.Day)) = True Then …..

Which felt pretty odd. It didn’t seem to work on the second line, unless I had the first line present. My variable nextEventDate is Nullable(Of Date) which means I was struggling a bit to get it to behave like a Date, so I had to separate it into Year, Month, Day and then rebuild these into a new DateTime.
The If Then statement seems pretty logical to me. Is that how you saw it being used?

Thanks for your support,

Alex

**Comment by alexstanier** [comment]
I don’t suppose you could recommend an MVC friendly calendar control could you?
Alex

**Comment by diaconesq** [comment]
JQueryUI date picker is an option. 
https://jqueryui.com/datepicker/

Bootstrap datepicker is another. It looks nicer out of the box.
https://github.com/eternicode/bootstrap-datepicker

There are probably good commercial offerings too, but I don't have any experience with any.
